<?php
require 'config.php';
require 'functions.php';

$conn = dbconn();

$migrations = [];
$migrations[] = [
    'title'    => 'added_skin_models_support',
    'function' => function (PDO $conn) {
        $conn->query('ALTER TABLE players ADD skin_model VARCHAR(64) DEFAULT NULL AFTER skin');
        $conn->query('ALTER TABLE players ADD cape VARCHAR(64) DEFAULT NULL AFTER isCapeOn');
        $conn->query('UPDATE players SET cape = player WHERE isCapeOn = TRUE');
        $conn->query('ALTER TABLE players DROP COLUMN isCapeOn');
    },
];

function migration_history_exist(PDO $conn): bool
{
    try {
        $result = $conn->query('SELECT TRUE FROM migration_history LIMIT 1');
    } catch (\PDOException $e) {
        return false;
    }
    return ($result !== false);
}

if (!migration_history_exist($conn)) {
    if ($conn->getAttribute(PDO::ATTR_DRIVER_NAME) !== 'mysql') {
        $autoIncrement = 'GENERATED BY DEFAULT AS IDENTITY';
        $timestampType = 'TIMESTAMP';
    } else {
        $autoIncrement = 'AUTO_INCREMENT';
        $timestampType = 'DATETIME';
    }
    $conn->query(sprintf(
        'CREATE TABLE migration_history ' .
        '(id INTEGER PRIMARY KEY %s, title VARCHAR(64) UNIQUE NOT NULL, timestamp %s DEFAULT CURRENT_TIMESTAMP)',
        $autoIncrement,
        $timestampType
    ));
}

$stmt = $conn->prepare('SELECT title FROM migration_history WHERE title = ?');
for ($i = 0, $count = count($migrations); $i < $count; ++$i) {
    $stmt->execute([$migrations[$i]['title']]);
    if ($stmt->rowCount() === 0) {
        $migrations[$i]['function']($conn);
        $insertStmt = $conn->prepare(
            'INSERT INTO migration_history (title) VALUES (?)'
        );
        $insertStmt->execute([$migrations[$i]['title']]);
    }
}
